<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb52a242d57ded37a642c2f34b9e0bba1
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb52a242d57ded37a642c2f34b9e0bba1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb52a242d57ded37a642c2f34b9e0bba1::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb52a242d57ded37a642c2f34b9e0bba1::$classMap;

        }, null, ClassLoader::class);
    }
}
